import { z } from "zod";

/**
Zod schema for distribution metadata generated by the registry.
*/
export const distSchema = z
	.object({
		/** Tarball URL. */
		tarball: z.string(),

		/** SHA1 sum of the tarball. */
		shasum: z.string(),

		/** String in the format `<hashAlgorithm>-<base64-hash>`. */
		integrity: z.string().optional(),

		/** Number of files in the tarball. */
		fileCount: z.number().optional(),

		/** Total unpacked size in bytes of the files in the tarball. */
		unpackedSize: z.number().optional(),

		/**
    PGP signature in the format `<package>@<version>:<integrity>`.

		@deprecated {@link https://docs.npmjs.com/about-registry-signatures#migrating-from-pgp-to-ecdsa-signatures}
		*/
		"npm-signature": z.string().optional(),

		/**
		ECDSA registry signatures.

		@see {@link https://docs.npmjs.com/about-registry-signatures}
    */
		signatures: z
			.array(
				z.object({
					keyid: z.string(),
					signature: z.string(),
				}),
			)
			.optional(),
	})
	.passthrough();

/**
`Dist` describes the distribution metadata generated by the registry.

@see {@link https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#dist}
*/
export type Dist = z.infer<typeof distSchema>;
