import { z } from "zod";
import { PackageJson } from "zod-package-json";

/**
`Dist` describes the distribution metadata generated by the registry.
@see {@link https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#dist}
*/
const Dist = z.object({
	/** Tarball URL. */
	tarball: z.string(),

	/** SHA1 sum of the tarball. */
	shasum: z.string(),

	/** String in the format `<hashAlgorithm>-<base64-hash>`. */
	integrity: z.string().optional(),

	/** Number of files in the tarball. */
	fileCount: z.number().optional(),

	/** Total unpacked size in bytes of the files in the tarball. */
	unpackedSize: z.number().optional(),

	/**
  PGP signature in the format `<package>@<version>:<integrity>`.
	@deprecated {@link https://docs.npmjs.com/about-registry-signatures#migrating-from-pgp-to-ecdsa-signatures}
	*/
	"npm-signature": z.string().optional(),

	/**
	ECDSA registry signatures.
	@see {@link https://docs.npmjs.com/about-registry-signatures}
  */
	signatures: z
		.array(
			z.object({
				keyid: z.string(),
				signature: z.string(),
			}),
		)
		.optional(),
});

export const PackageManifest = PackageJson.extend({
	/** Package version ID in the format `<name>@<version>`. */
	_id: z.string(),

	/** Distribution metadata generated by the registry. */
	dist: Dist,

	/** Text extracted from the README file. */
	readme: z.string().optional(),

	/** Name of the README file. */
	readmeFilename: z.string().optional(),

	/** Commit corresponding to the published package version. */
	gitHead: z.string().optional(),

	/** True if the package contains a shrinkwrap file. */
	_hasShrinkwrap: z.boolean().optional(),

	/** Node.js version used to publish the package. */
	_nodeVersion: z.string().optional(),

	/** npm CLI version used to publish the package. */
	_npmVersion: z.string().optional(),

	/** npm user who published the specific version of the package. */
	_npmUser: PackageJson.shape.author.optional(),

	/** Internal npm registry data. */
	_npmOperationalInternal: z
		.object({
			host: z.string().optional(),
			tmp: z.string().optional(),
		})
		.optional(),
});

/**
`PackageManifest` describes the manifest for a specific version of a package (e.g., `foo@1.0.0`).

@remarks
The manifest contains data extracted from `package.json` as well as data generated by the registry.

@see {@link https://docs.npmjs.com/cli/v10/configuring-npm/package-json}
@see {@link https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#getpackageversion}
@see {@link https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#abbreviated-version-object}
@see {@link https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#full-metadata-format}
@see {@link https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#version}
*/
export type PackageManifest = z.infer<typeof PackageManifest>;
