import { z } from "zod";
import { distSchema } from "./dist";

/**
Zod schema for the package manifest.
*/
export const packageManifestSchema = z.object({
	/** Package name. */
	name: z.string(),

	/** Package semver version number. */
	version: z.string(),

	/** Distribution metadata generated by the registry. */
	dist: distSchema,
});

/**
Manifest describing a specific version of a package (e.g., `foo@1.0.0`).

@remarks
The manifest contains data extracted from the `package.json` file as well as data generated by the registry.

@see {@link https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#getpackageversion}
@see {@link https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#abbreviated-version-object}
@see {@link https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#full-metadata-format}
@see {@link https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#version}
*/
export type PackageManifest = z.infer<typeof packageManifestSchema>;
